post:
  tags:
    - Settings
  summary: Update look and feel settings
  description: |-
    Updates the look and feel settings for the site or for a single space.
    If custom settings exist, they are updated. If no custom settings exist,
    then a set of custom settings is created.

    Note, if a theme is selected for a space, the space look and feel settings
    are provided by the theme and cannot be overridden.

    **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
    'Admin' permission for the space.
  operationId: updateLookAndFeelSettings
  parameters:
    - name: spaceKey
      in: query
      description: |-
        The key of the space for which the look and feel settings will be
        updated. If this is not set, the global look and feel settings will
        be updated.
      schema:
        type: string
  requestBody:
    description: >-
      The updated settings. All values for the settings must be included,

      regardless of whether they are being changed.


      One way to create the request body is to copy the settings from the

      response body of [Get look and feel
      settings](#api-settings-lookandfeel-get)

      and modify it as needed.
    content:
      application/json:
        schema:
          $ref: ../components/schemas/LookAndFeel.yaml
    required: true
  responses:
    '200':
      description: Returned if the look and feel settings are updated.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/LookAndFeelWithLinks.yaml
    '400':
      description: |-
        Returned if;

        - The `spaceKey` is invalid
        - The request body contains invalid data.
      content: {}
    '403':
      description: |-
        Returned if the calling user doesn't have permission to edit the
        look and feel settings.
      content: {}
    '404':
      description: Returned if there is no space with the given `spaceKey`.
      content: {}
  security:
    - oAuthDefinitions:
        - manage:confluence-configuration
    - basicAuth: []
  x-atlassian-oauth2-scopes:
    - scheme: oAuthDefinitions
      state: Current
      scopes:
        - manage:confluence-configuration
    - scheme: oAuthDefinitions
      state: Beta
      scopes:
        - read:configuration:confluence
        - read:space.setting:confluence
        - write:configuration:confluence
        - write:space.setting:confluence
  x-codegen-request-body-name: body
  x-atlassian-connect-scope: WRITE
delete:
  tags:
    - Settings
  summary: Reset look and feel settings
  description: |-
    Resets the custom look and feel settings for the site or a single space.
    This changes the values of the custom settings to be the same as the
    default settings. It does not change which settings (default or custom)
    are selected. Note, the default space settings are inherited from the
    current global settings.

    **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
    'Admin' permission for the space.
  operationId: resetLookAndFeelSettings
  parameters:
    - name: spaceKey
      in: query
      description: |-
        The key of the space for which the look and feel settings will be
        reset. If this is not set, the global look and feel settings will
        be reset.
      schema:
        type: string
  responses:
    '204':
      description: Returned if the look and feel settings have been reset.
      content: {}
    '400':
      description: Returned if `spaceKey` is invalid.
      content: {}
    '403':
      description: |-
        Returned if the calling user doesn't have permission to reset the
        look and feel.
      content: {}
    '404':
      description: Returned if there is no space with the given `spaceKey`.
      content: {}
  security:
    - oAuthDefinitions:
        - manage:confluence-configuration
    - basicAuth: []
  x-atlassian-oauth2-scopes:
    - scheme: oAuthDefinitions
      state: Current
      scopes:
        - manage:confluence-configuration
    - scheme: oAuthDefinitions
      state: Beta
      scopes:
        - write:configuration:confluence
        - write:space.setting:confluence
  x-atlassian-connect-scope: DELETE
